FROM ubuntu:kinetic-20221101
FROM python:3.9

# Replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh


# Build this Dockerfile with the following command: 
# docker build --no-cache --build-arg USRNM=$(whoami) --build-arg USRUID=$(id -u) --build-arg USRGID=$(id -g) -t hashrocket:latest .
# This ensures that you will have the right permissions inside docker

# User and group variables
ARG USRNM
ARG USRUID
ARG USRGID

# Create user and add to the specified group
RUN groupadd -g $USRGID $USRNM || echo "Could not create group with GID $USRGID".
RUN useradd -g $USRGID -u $USRUID -m $USRNM

# install sudo
RUN apt-get update && apt-get -y install sudo
     
# Add user to sudoers
RUN adduser $USRNM sudo

# Ensure sudo group users are not 
# asked for a password when using 
# sudo command by ammending sudoers file
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers


RUN echo 'alias ll="ls -lah"' >> /home/$USRNM/.bashrc

# make sure apt is up to date
RUN apt-get update --fix-missing && apt-get -yq dist-upgrade && \
apt-get install --no-install-recommends -yq nano && \
apt-get install --no-install-recommends -yq htop && \
apt-get install --no-install-recommends -yq rsync && \
apt-get install --no-install-recommends -yq lsof && \
apt-get install --no-install-recommends -yq zip && \
apt-get install --no-install-recommends -yq unzip && \
apt-get install --no-install-recommends -yq wget && \
apt-get install --no-install-recommends -yq git

USER $USRNM

# RUN pip install Flask==2.2.2
# RUN pip install web3==5.31.1

# Install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y

RUN echo 'source $HOME/.cargo/env' >> $HOME/.bashrc

ENTRYPOINT "/bin/bash"